version: "3.7"
services:
    mysql:
        image: mysql:latest
        container_name: curso-ifes_mysql_1  
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=cursoifes
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql/:/var/lib/mysql
        networks:
            - rede_docker
    php:
        image: php:latest     
        build: ./docker/php
        container_name: curso-ifes_php_1php
        ports:
        - 9000:9000
        volumes:
            - ./www:/usr/share/nginx/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=cursoifes
            - MYSQL_DRIVER=pdo_mysql
            - MYSQL_HOST=mysql
        networks:
            - rede_docker
    nginx:
        container_name: curso-ifes_nginx_1 
        image: "nginx:latest"
        volumes:
            - ./www:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9999:80"
        depends_on:
            - "php"
        networks:
            - rede_docker
networks:
    rede_docker:
        driver: bridge