version: "3.7"
services:
    mysql:
        image: mysql:latest        
        
        environment:
            - MYSQL_DATABASE=cursoifes
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root            
        ports:
            - 3306:3306
        volumes:
            - ./mysql/var/lib/mysql/ 
        networks:
            - rede_docker
    php:
        image: php:latest 

        build: ./docker/php        
        ports:
        - 9000:9000
        volumes:
            - ./www:/usr/share/nginx/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=cursoifes
            - MYSQL_DRIVER=pdo_mysql
            - MYSQL_HOST=mysql
        networks:
            - rede_docker
    nginx:
        
        image: "nginx:latest"
        volumes:
            - ./www:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9999:80"
        depends_on:
            - "php"
        networks:
            - rede_docker
networks:
    rede_docker:
        driver: bridge